import { dana } from "@/utils/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" className={dana.className} dir="rtl">
      <body>{children}</body>
    </html>
  );
}
