import { dana } from "@/utils/fonts";
import "@/styles/app.css";
import { ThemeProviders } from "@/providers/ThemeProviders";
import Header from "@/layout/Header";
import MobileHeader from "@/layout/MobileHeader";
import MobileMenu from "@/layout/MobileMenu";
import Providers from "../Redux/Providers";
import NextAuthProvider from "@/providers/NextAuthProvider";
import { SessionProvider } from "next-auth/react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // icons: {
  //   icon: '/icon.png', // /public path
  // },
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="fa"
      className={dana.className}
      dir="rtl"
      suppressHydrationWarning
    >
      <body className="bg-gray-100 dark:bg-zinc-800">
        <NextAuthProvider>
        {/* <SessionProvider session={session}> */}

          <ThemeProviders>
            <Providers>
              <Header />
              <MobileHeader />
              <MobileMenu />
              {/* <ThemeSwitch/> */}
              {children}
            </Providers>
          </ThemeProviders>
          {/* </SessionProvider> */}
        </NextAuthProvider>
      </body>
    </html>
  );
}
